#!/bin/bash
# 2 Minutes Terminal Dj using cmus

mix(){ cmus-remote -n -k 40; }
dj(){ while [ 1==1 ]; do mix; sleep 16; done };

nohup cmus &
echo "Warning nohup may cause size of nohup.out in GBs when played for a longer time..."
cmus-remote -p
echo "Running termDJ, Ctrl+C to break"
dj
